apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: vertex-ai-cloud-deploy-pipeline
serialPipeline:
  stages:
  - targetId: prod-endpoint

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-endpoint
customTarget:
  customTargetType: vertex-ai-endpoint
deployParameters:
  vertexAIEndpoint: projects/angel-gcp-starter-project2/locations/us-central1/endpoints/prod
  vertexAIConfigPath: "prod"
  vertexAIMinReplicaCount: "3"
