apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: k8s-cleanup-qs
description: pipeline that includes a post-deploy hook to clean up resources
serialPipeline:
  stages:
  - targetId: k8s-cleanup-qs-prod
    profiles: []
    strategy:
      standard:
        postdeploy:
          actions: ["cleanup-action"]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: k8s-cleanup-qs-prod
description: k8s-cleanup quickstart prod cluster
gke:
  cluster: projects/$PROJECT_ID/locations/$REGION/clusters/$CLUSTER_ID
