apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-cleanup-deployment-orig
  labels:
    app: my-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: my-app-image
