apiVersion: skaffold/v4beta7
kind: Config
manifests:
  rawYaml:
  - kubernetes.yaml
deploy:
  kubectl: {}
customActions:
- name: postdeploy-action
  containers:
  - name: clean-up-image
    # Replace the below with the image you built from this code, for example:
    # us-central1-docker.pkg.dev/my-project/my-repo/clean-up-image:latest
    image: us-central1-docker.pkg.dev/minnah-easymode-testing/clean-up/clean-up-image:latest
    command: ["/cleanup-kubernetes-resources"]
    # If you only want to delete resources in specific namespaces uncomment the 
    # namespace line below and update with your values to pass command line args
    # to the container. 
    # If you want to add to the existing default resource-types to delete, 
    # uncomment the resource-type line below and add to it. If you want to
    # delete all resources, pass in "all" as the resource-type.
    args:
    # - --namespace=foo,bar
    # - --resource-type=service,cronjob.batch,job.batch,deployment.apps,replicaset.apps,statefulset.apps,pod,configmap,secret,horizontalpodautoscaler.autoscaling